version: '3'
services:
  notebook:
    container_name: python_notebook
    labels:
      name: jupyter notebook
    ports:
      - "8888:8888"
    volumes:
      - ~/Documents/notebooks:/home/notebooks
    build: .
    command: jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root